// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateIdentity(arg1) {
  return window['go']['main']['App']['ActivateIdentity'](arg1);
}

export function AddIdentity(arg1) {
  return window['go']['main']['App']['AddIdentity'](arg1);
}

export function BindRepository(arg1) {
  return window['go']['main']['App']['BindRepository'](arg1);
}

export function ChooseExportArchivePath() {
  return window['go']['main']['App']['ChooseExportArchivePath']();
}

export function ChooseIdentityPath() {
  return window['go']['main']['App']['ChooseIdentityPath']();
}

export function ChooseImportArchivePath() {
  return window['go']['main']['App']['ChooseImportArchivePath']();
}

export function ChooseRepositoryPath() {
  return window['go']['main']['App']['ChooseRepositoryPath']();
}

export function DeleteIdentity(arg1) {
  return window['go']['main']['App']['DeleteIdentity'](arg1);
}

export function DetectIdentity(arg1) {
  return window['go']['main']['App']['DetectIdentity'](arg1);
}

export function ExportBackup(arg1) {
  return window['go']['main']['App']['ExportBackup'](arg1);
}

export function GetActiveIdentity() {
  return window['go']['main']['App']['GetActiveIdentity']();
}

export function GetDoctorStatus() {
  return window['go']['main']['App']['GetDoctorStatus']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ImportBackup(arg1) {
  return window['go']['main']['App']['ImportBackup'](arg1);
}

export function ListIdentities() {
  return window['go']['main']['App']['ListIdentities']();
}

export function RemoveRepositoryBinding(arg1) {
  return window['go']['main']['App']['RemoveRepositoryBinding'](arg1);
}

export function SyncDetectedIdentity(arg1) {
  return window['go']['main']['App']['SyncDetectedIdentity'](arg1);
}

export function UpdateIdentity(arg1) {
  return window['go']['main']['App']['UpdateIdentity'](arg1);
}
