// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateIdentity(arg1) {
  return window['go']['main']['App']['ActivateIdentity'](arg1);
}

export function AddIdentity(arg1) {
  return window['go']['main']['App']['AddIdentity'](arg1);
}

export function DeleteIdentity(arg1) {
  return window['go']['main']['App']['DeleteIdentity'](arg1);
}

export function GetActiveIdentity() {
  return window['go']['main']['App']['GetActiveIdentity']();
}

export function GetDoctorStatus() {
  return window['go']['main']['App']['GetDoctorStatus']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListIdentities() {
  return window['go']['main']['App']['ListIdentities']();
}

export function UpdateIdentity(arg1) {
  return window['go']['main']['App']['UpdateIdentity'](arg1);
}
